---
name: Lint

on:
    pull_request:
        branches: 
            - main

permissions:
    contents: write

jobs:
    lint:
        name: lint
        permissions:
            contents: write
            statuses: write

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Run super-linter
              uses: super-linter/super-linter@v7.2.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  # Only run linter on changed files in the PR
                  VALIDATE_ALL_CODEBASE: false 
                  # Set language specific flags
                  VALIDATE_CHECKOV: false
                  VALIDATE_JSCPD: false
                  # Set flags that default as false to true
                  FIX_CLANG_FORMAT: true
                  FIX_JAVASCRIPT_PRETTIER: true

            - name: Commit and push linting fixes
              if: >
                  github.event_name == 'pull_request' &&
                  github.ref_name != github.event.repository.default_branch
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
                  commit_message: "Chore: Fixed linting issues"
                  commit_user_name: super-linter
                  commit_user_email: super-linter@super-linter.dev